### ISSUE TITLE
easy_install deprecated

### ISSUE THREAD

**Issue by bhavers** [tkurki/marinepi-provisioning#70]
easy_install is deprecated, and therefor installing pysk will not work.
I think roles/pysk/task/main.yml should be changed. Something like this?

```
- pip:
    name: pysk
    version: latest
  become: true
#- name: 'Install pysk'
#  easy_install:
#    name: pysk
#    state: latest
#  become: true
```

also opened an issue in the pysk project: https://github.com/ph1l/pysk/issues/5
